server:
  port: 30000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GGKDbWBT4SLvtN9EH2r
      secret-key: Wb2Ya70Ym5x7PLmNC2PhQQj5ZehCT4
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: catmall
  application:
    name: mall-third-party